# Base configs
baseurl: "https://prova1.netlify.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio"
subtitle: "See the world through my eyes!"
author: "ciukamama"
header:
 title: "Photography"
 subtitle: "by ciukamama"
footer:
 name: "Hey there, my name is Marco"
 bio: 
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: 
  twitter: 
  instagram: "https://www.instagram.com/ciukamama"
  dribbble: 
  linkedin: 
  github: 
