# Base configs
baseurl: "https://prova1.netlify.com/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Ciukamama"
subtitle: "See the world through my eyes!"
author: "Ciukamama"
header:
 title: "Istanti"
 subtitle: "di Ciukamama"
footer:
 name: 
 bio: 
 github: 
web_design: "MM"
social_urls:
  facebook: "https://www.facebook.com/noz1993"
  twitter: 
  instagram: "https://www.instagram.com/ciukamama"
  dribbble: 
  linkedin: 
  github: 
