# Base configs
baseurl: "https://prova1.netlify.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio"
subtitle: "See the world through my eyes!"
author: "ciukamama"
header:
 title: "Istanti"
 subtitle: "by ciukamama"
footer: "SEGUIMI SU"
 name: 
 bio: 
 github: 
web_design: "MM"
social_urls:
  facebook: "https://www.facebook.com/Noz1993"
  twitter: 
  instagram: "https://www.instagram.com/ciukamama"
  dribbble: 
  linkedin: 
  github: 
